# tenant-config-a.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-config-a
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/eventuate_a?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_USERNAME: eventuate_a
